### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Wang-yu-long** [mohamadhabash/VisualBERT-for-Memes-Classification#1]
I am a fresher，please，How should the dataset be organized？

**Comment by mohamadhabash** [comment]
@Wang-yu-long to prepare the dataset, follow these steps:

1. Generate the visual embeddings for your images using `Visual_Embeddings_for_VisualBERT_Using_Detectron2.ipynb` notebook. Under the title **Visual Embeddings for All Images** in the notebook, you can read the images, convert them to BGR format, and then generate the visual embeddings. Finally, save the `visual_embeds` list as a `.pkl` file using `pickle` library.
2. In `VisualBERT.ipynb` notebook: 
    1. You should have a `csv` file (in my case called `training.csv`) containing image file name, labels, and text, and put its content in a dataframe `df`. **Please make sure image names in the dataframe and the visual embeddings generated previously are aligned!** 
    
    2. After that, you can load the `.pkl` file to get the visual embeddings (in my case called `visual_embeds_mami.pkl`) 
    
    3. Use the visual embeddings and the dataframe `df` to create the dataset of type `MAMIDataset`, as in the notebook.
    
I hope my explanation is clear enough. Good luck :)
